namespace PipedAgents.Strands

open System
open Fable.Core
open Fable.Core.JsInterop

type [<AllowNullLiteral>] AsyncIterable<'T> =
    inherit JS.AsyncIterable
    [<Emit("$0[Symbol.asyncIterator]()")>]
    abstract asyncIterator: unit -> AsyncIterator<'T>

and [<AllowNullLiteral>] IteratorResult<'T> =
    abstract value: 'T with get, set
    abstract ``done``: bool with get, set

and [<AllowNullLiteral>] AsyncIterator<'T> =
    abstract next: unit -> JS.Promise<IteratorResult<'T>>
    abstract ``return``: value: 'T -> JS.Promise<IteratorResult<'T>>
    abstract throw: e: obj -> JS.Promise<IteratorResult<'T>>

and [<AllowNullLiteral>] AsyncGenerator<'T> =
    inherit AsyncIterator<'T>
    inherit AsyncIterable<'T>

/// <summary>
/// Message role in a conversation between user and assistant.
/// </summary>
[<StringEnum>]
type Role =
    | User
    | Assistant

and AgentData =
    /// Agent state storage accessible to tools and application logic.
    abstract state: obj
    /// The conversation history of messages between user and assistant.
    abstract messages: Message array

and ToolSpec = {
    /// The unique name of the tool.
    name: string
    /// A description of what the tool does.
    description: string
    /// JSON Schema defining the expected input structure for the tool.
    inputSchema: obj option
}

and ToolUse =
    /// The name of the tool to execute.
    abstract name: string
    /// Unique identifier for this tool use instance.
    /// Used to match tool results back to their requests.
    abstract toolUseId: string
    /// The input parameters for the tool.
    /// Must be JSON-serializable.
    abstract input: obj

and Reasoning =
    /// The reasoning text generated by the agent.
    abstract text: string
    /// Optional signature for verifying reasoning authenticity.
    abstract signature: string option
    /// Optional redacted content in binary format.
    abstract redactedContent: byte array option

and ToolContext =
    /// The tool use request that triggered this tool execution.
    /// Contains the tool name, toolUseId, and input parameters.
    abstract toolUse: ToolUse
    /// The agent instance that is executing this tool.
    /// Provides access to agent state and other agent-level information.
    abstract agent: AgentData

and ToolStreamEventData =
    /// Caller-provided data for the progress update.
    /// Can be any type of data the tool wants to report.
    abstract data: obj option

and [<TypeScriptTaggedUnion("type")>] ToolResultContent =
    | TextBlock of text: string
    | JsonBlock of json: obj

and [<StringEnum>] ToolResultStatus =
    | Success
    | Error

and ToolResult =
    /// Unique identifier matching the tool use request.
    abstract toolUseId: string
    /// Status of the tool execution (e.g., "success", "error").
    abstract status: ToolResultStatus
    /// Array of content blocks returned by the tool.
    abstract content: ToolResultContent array
    /// Optional error information if the tool execution failed.
    abstract error: exn option

and Tool =
    /// The unique name of the tool.
    abstract name: string
    /// Human-readable description of what the tool does.
    abstract description: string
    /// OpenAPI JSON specification for the tool.
    abstract toolSpec: ToolSpec
    /// Executes the tool with streaming support.
    abstract stream: toolContext: ToolContext -> AsyncGenerator<ToolStreamEventData>

and [<TypeScriptTaggedUnion("type")>] ContentBlock =
    /// Plain text content
    | TextBlock of text: string
    /// Tool usage request with parameters
    | ToolUseBlock of ToolUse
    /// Result from tool execution
    | ToolResultBlock of ToolResult
    /// AI reasoning process content (may be redacted)
    | ReasoningBlock of Reasoning
    /// Cache point marker for prompt caching
    | CachePointBlock of cacheType: string
    /// Content for guardrail evaluation
    | GuardContentBlock of text: obj option * image: obj option
    /// Image content with format and source
    | ImageBlock of format: string * source: obj
    /// Video content with format and source
    | VideoBlock of format: string * source: obj
    /// Document content with format and source
    | DocumentBlock of format: string * source: obj
    /// Structured JSON data
    | JsonBlock of json: obj

and Message = {
    Role: Role
    Content: ContentBlock array
}

[<TypeScriptTaggedUnion("type")>]
type ContentBlockDelta =
    | TextDelta of text: string
    | ToolUseDelta of input: string
    | ReasoningDelta of Reasoning

type Usage =
    /// Number of input tokens processed
    abstract inputTokens: int
    /// Number of output tokens generated
    abstract outputTokens: int
    /// Total number of tokens (input + output)
    abstract totalTokens: int
    /// Number of cache read input tokens (optional)
    abstract cacheReadInputTokens: int option
    /// Number of cache write input tokens (optional)
    abstract cacheWriteInputTokens: int option

type Metrics =
    /// Latency in milliseconds.
    abstract latencyMs: int

type AgentResult =
    /// Reason for stopping the agent execution.
    abstract stopReason: string
    /// The last message generated by the agent.
    abstract lastMessage: Message

type S3Location =
    /// The S3 URI of the object (e.g., "s3://bucket/key").
    abstract uri: string
    /// The AWS account ID of the bucket owner (optional).
    abstract bucketOwner: string option

[<TypeScriptTaggedUnion("type")>]
type ImageSource =
    /// Image source as raw bytes.
    | ImageSourceBytes of bytes: byte array
    /// Image source from S3 location
    | ImageSourceS3Location of S3Location
    /// Image source from URL.
    | ImageSourceUrl of url: string

type ImageBlockData =
    /// Image format (e.g., "png", "jpeg").
    abstract format: string
    /// Image source data (URL, base64, etc.).
    abstract source: ImageSource

[<TypeScriptTaggedUnion("type")>]
type VideoSource =
    /// Video source as raw bytes.
    | VideoSourceBytes of bytes: byte array
    /// Video source from S3 location
    | VideoSourceS3Location of S3Location

type VideoBlockData =
    /// Video format (e.g., "mp4", "webm").
    abstract format: string
    /// Video source data (URL, base64, etc.).
    abstract source: VideoSource

type DocumentSource =
    /// Document source as raw bytes.
    | DocumentSourceBytes of bytes: byte array
    /// Document source as text.
    | DocumentSourceText of text: string
    /// Document source as content blocks.
    | DocumentSourceContentBlock of content: {| text: string |} array
    /// Document source from S3 location
    | DocumentSourceS3Location of S3Location

type DocumentBlockData =
    /// Document name.
    abstract name: string
    /// Document format.
    abstract format: string
    /// Document source.
    abstract source: obj
    /// Citation configuration.
    abstract citations: {| enabled: bool |} option
    /// Context information for the document.
    abstract context: string option

[<TypeScriptTaggedUnion("type")>]
type ModelStreamEventOrContent =
    /// Model streaming event
    | ModelMessageStartEvent of role: Role
    | ModelContentBlockStartEvent of start: obj
    | ModelContentBlockDeltaEvent of delta: ContentBlockDelta
    | ModelContentBlockStopEvent
    | ModelMessageStopEvent of stopReason: string * additionalModelResponseFields: obj
    | ModelMetadataEvent of usage: Usage * metrics: Metrics * trace : obj
    /// Content block
    | TextBlock of text: string
    | ToolUseBlock of ToolUse
    | ToolResultBlock of ToolResult
    | ReasoningBlock of Reasoning
    | CachePointBlock of cacheType: string
    | ImageBlock of format: string * source: ImageBlockData
    | VideoBlock of format: string * source: VideoBlockData
    | DocumentBlock of format: string * source: DocumentBlockData
    | JsonBlock of json: obj

/// <summary>
/// Stream events that can be emitted during agent execution.
/// Provides real-time updates on agent processing steps.
/// </summary>
[<TypeScriptTaggedUnion("type")>]
type AgentStreamEvent =
    /// Model streaming event
    | ModelMessageStartEvent of role: Role
    | ModelContentBlockStartEvent of start: obj
    | ModelContentBlockDeltaEvent of delta: ContentBlockDelta
    | ModelContentBlockStopEvent
    | ModelMessageStopEvent of stopReason: string * additionalModelResponseFields: obj
    | ModelMetadataEvent of usage: Usage * metrics: Metrics * trace : obj
    /// Content block
    | TextBlock of text: string
    | ToolUseBlock of ToolUse
    | ToolResultBlock of ToolResult
    | ReasoningBlock of Reasoning
    | CachePointBlock of cacheType: string
    | ImageBlock of format: string * source: ImageBlockData
    | VideoBlock of format: string * source: VideoBlockData
    | DocumentBlock of format: string * source: DocumentBlockData
    | JsonBlock of json: obj
    /// Other events
    | ToolStreamEvent of obj
    | BeforeInvocationEvent of agent: AgentData
    | AfterInvocationEvent of agent: AgentData
    | BeforeModelCallEvent of agent: AgentData
    | AfterModelCallEvent of agent: AgentData
    | BeforeToolsEvent of agent: AgentData * message: Message
    | AfterToolsEvent of agent: AgentData * message: Message
    | BeforeToolCallEvent of agent: AgentData * toolUse: ToolUse * tool: Tool
    | AfterToolCallEvent of agent: AgentData * toolUse: ToolUse * tool: Tool * result: ToolResult * error: exn option
    | MessageAddedEvent of agent: AgentData * message: Message
    | ModelStreamEventHook of agent: AgentData * event: ModelStreamEventOrContent
    | AgentResult of AgentResult

/// <summary>
/// Agent configuration options.
/// Directly wraps a JavaScript object for efficient interop with the Strands SDK.
/// </summary>
type AgentOptions() =
    let jsObj = !!{| printer = false |}
    
    /// The model instance or string model ID to use (overrides default)
    member this.Model with set (value: obj) = jsObj?model <- value
    /// Initial conversation history
    member this.Messages with set (value: Message array) = jsObj?messages <- value
    /// Tools available to the agent (nested arrays are flattened)
    member this.Tools with set (value: Tool array) = jsObj?tools <- value
    /// System prompt to guide agent behavior
    member this.SystemPrompt with set (value: string) = jsObj?systemPrompt <- value
    /// Initial state values for the agent
    member this.State with set (value: obj) = jsObj?state <- obj
    /// Enable automatic console output printing
    member this.Printer with set (value: bool) = jsObj?printer <- value
    /// Conversation manager for handling message history
    member this.ConversationManager with set (value: obj) = jsObj?conversationManager <- value
    /// Hook providers for extending agent behavior
    member this.Hooks with set (value: obj array) = jsObj?hooks <- value

    member internal this.ToJS() = jsObj

/// <summary>
/// OpenAI client configuration options.
/// Directly wraps a JavaScript object for efficient interop with the OpenAI SDK.
/// </summary>
type OpenAIClientOptions() =
    let jsObj = !!{| |}
    let getClientConfig () =
        if isNull jsObj?clientConfig then
            jsObj?clientConfig <- !!{| |}
        jsObj?clientConfig
    /// API key (falls back to environment variable if not provided)
    member this.ApiKey with set (value: string) = jsObj?apiKey <- value
    /// Sampling temperature (0.0 to 2.0)
    member this.Temperature with set (value: Nullable<float>) = if value.HasValue then jsObj?temperature <- value.Value
    /// Maximum tokens to generate
    member this.MaxTokens with set (value: Nullable<int>) = if value.HasValue then jsObj?maxTokens <- value.Value
    /// Top-p sampling parameter
    member this.TopP with set (value: Nullable<float>) = if value.HasValue then jsObj?topP <- value.Value
    /// Frequency penalty (-2.0 to 2.0)
    member this.FrequencyPenalty with set (value: Nullable<float>) = if value.HasValue then jsObj?frequencyPenalty <- value.Value
    /// Presence penalty (-2.0 to 2.0)
    member this.PresencePenalty with set (value: Nullable<float>) = if value.HasValue then jsObj?presencePenalty <- value.Value
    /// Custom base URL for API requests
    member this.BaseURL with set (value: string) = (getClientConfig())?baseURL <- value
    /// Request timeout in milliseconds
    member this.Timeout with set (value: Nullable<int>) = if value.HasValue then (getClientConfig())?timeout <- value.Value

    member internal this.ToJS() = jsObj


/// <summary>
/// Low-level JavaScript binding for the Agent class from @strands-agents/sdk.
/// This type provides direct access to the JavaScript Agent constructor and methods.
/// </summary>
[<Import("Agent", "@strands-agents/sdk")>]
type Agent(config: obj) =
    /// <summary>
    /// Invokes the agent with the provided input and returns a Promise of the result.
    /// </summary>
    /// <param name="args">Input arguments - can be string, ContentBlock[], or Message[]</param>
    /// <returns>Promise that resolves to AgentResult</returns>
    member _.invoke(args: string): JS.Promise<AgentResult> = jsNative
    member _.invoke(args: ContentBlock[]): JS.Promise<AgentResult> = jsNative
    member _.invoke(args: Message[]): JS.Promise<AgentResult> = jsNative

    /// <summary>
    /// Streams the agent execution, yielding events and returning the final result.
    /// </summary>
    /// <param name="args">Input arguments - can be string, ContentBlock[], or Message[]</param>
    /// <returns>AsyncGenerator that yields AgentStreamEvent objects</returns>
    member _.stream(args: string): AsyncGenerator<AgentStreamEvent> = jsNative
    member _.stream(args: ContentBlock[]): AsyncGenerator<AgentStreamEvent> = jsNative
    member _.stream(args: Message[]): AsyncGenerator<AgentStreamEvent> = jsNative

/// <summary>
/// Low-level JavaScript binding for the OpenAIModel class from @strands-agents/sdk/openai.
/// This type provides direct access to the JavaScript OpenAIModel constructor and methods.
/// </summary>
[<Import("OpenAIModel", "@strands-agents/sdk/openai")>]
type JSOpenAIModel(config: obj) =
    /// <summary>
    /// Updates the model configuration by merging with existing settings.
    /// </summary>
    /// <param name="modelConfig">Configuration object with model-specific settings to update</param>
    member _.updateConfig(modelConfig: obj): unit = jsNative

    /// <summary>
    /// Retrieves the current model configuration.
    /// </summary>
    /// <returns>The current configuration object</returns>
    member _.getConfig(): obj = jsNative
